addons: 
  apt:
    packages:
      - graphviz
before_cache: 
  - "rm -rf $HOME/.m2/repository/org/ligoj/bootstrap"
  - "find $HOME/.m2 -name resolver-status.properties -exec rm {} \\;"
before_install:
  - "chmod +x ./travis.sh"
cache: false
jdk: openjdk10
env: 
  - TARGET=BUILD
branches:
  only:
    - master
    - dev
language: java
notifications: 
  email: false
sudo: false
script: "./travis.sh"
