addons: 
  apt:
    packages:
      - graphviz
before_cache: 
  - "rm -rf $HOME/.m2/repository/org/ligoj/bootstrap"
  - "find $HOME/.m2 -name resolver-status.properties -exec rm {} \\;"
cache: 
  directories: 
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
    - $HOME/jvm
    - $HOME/maven
matrix:
  include:
    - jdk: openjdk10
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - "chmod +x ./travis.sh"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      script: "./travis.sh"
env: 
  - TARGET=BUILD
branches:
  only:
    - master
    - dev
language: java
notifications: 
  email: false
sudo: false
